/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Internal.PerfilUsuario;
import model.Usuario;


/**
 *
 * @author James
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    private final Usuario usuarioLogado;
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal(Usuario usuarioLogado) {
        this.usuarioLogado = usuarioLogado;
        initComponents();
//       this.usuario.setText(usuarioLogado.getUsuario());
//       this.email.setText(usuarioLogado.getEmail());
//       this.nomeCompleto.setText(usuarioLogado.getNomeCompleto());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelControle = new javax.swing.JDesktopPane();
        ButaoPerfil = new javax.swing.JButton();
        ButaoProjeto = new javax.swing.JButton();
        ButaoSair = new javax.swing.JButton();
        Janelas = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ButaoPerfil.setText("Perfil");
        ButaoPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButaoPerfilActionPerformed(evt);
            }
        });

        ButaoProjeto.setText("Projeto");

        ButaoSair.setText("Sair");

        PainelControle.setLayer(ButaoPerfil, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PainelControle.setLayer(ButaoProjeto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PainelControle.setLayer(ButaoSair, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout PainelControleLayout = new javax.swing.GroupLayout(PainelControle);
        PainelControle.setLayout(PainelControleLayout);
        PainelControleLayout.setHorizontalGroup(
            PainelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelControleLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PainelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ButaoPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButaoSair, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButaoProjeto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                .addContainerGap())
        );
        PainelControleLayout.setVerticalGroup(
            PainelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelControleLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(ButaoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(ButaoProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(ButaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JanelasLayout = new javax.swing.GroupLayout(Janelas);
        Janelas.setLayout(JanelasLayout);
        JanelasLayout.setHorizontalGroup(
            JanelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
        );
        JanelasLayout.setVerticalGroup(
            JanelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PainelControle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Janelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(657, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Janelas, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PainelControle))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButaoPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButaoPerfilActionPerformed
        PerfilUsuario perfil = new PerfilUsuario(usuarioLogado);
        Janelas.add(perfil);
        perfil.setVisible(true);
    }//GEN-LAST:event_ButaoPerfilActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButaoPerfil;
    private javax.swing.JButton ButaoProjeto;
    private javax.swing.JButton ButaoSair;
    private javax.swing.JDesktopPane Janelas;
    private javax.swing.JDesktopPane PainelControle;
    // End of variables declaration//GEN-END:variables
}
